In [76]:
#o	Create a 1D array of numbers from 10 to 50.
import numpy as np
arr=np.arange(1,51,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [77]:
#	Create a 3x3 array of random numbers between 0 and 1.
a1=np.random.rand(3,3)
a1

array([[0.88285422, 0.08109994, 0.8733316 ],
       [0.12818812, 0.74844844, 0.09046551],
       [0.13599085, 0.44411879, 0.59612001]])

In [78]:
#o	Find the shape, size, and data type of the array you created in the previous task.
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(50,)
50
int64
1


In [79]:
#o	Find the shape, size, and data type of the array you created in the previous task.
print(a1.shape)
print(a1.size)
print(a1.dtype)
print(a1.ndim)

(3, 3)
9
float64
2


In [80]:
#	Add 5 to every element of a 1D array.
k=arr+5
k

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55])

In [81]:
#	Multiply two 2D arrays element-wise.
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
mul=arr1*arr2
mul

array([[ 5, 12],
       [21, 32]])

In [82]:
#o	Create a 5x5 array of integers from 1 to 25. Extract:
#The first row.
#	The last column.
#	A subarray of the first three rows and first two columns

five_array=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
five_array


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [83]:

print(five_array[0:1,0:5])

[[1 2 3 4 5]]


In [84]:

print(five_array[0:5,4:5])

[[ 5]
 [10]
 [15]
 [20]
 [25]]


In [85]:

print(five_array[0:3,0:2])

[[ 1  2]
 [ 6  7]
 [11 12]]


In [86]:

#	Create a 10-element array of random integers between 1 and 100. Find:
#	The maximum value.
#	The minimum value.
#	The mean and standard deviation.
a=np.random.randint(1,100,10)
print(a)
max_value=a.max()
print(max_value)
min_value=a.min()
print(min_value)
mean=a.mean()
print(mean)
standard_deviation=a.std()

print(standard_deviation)

[70 93 81 13 95 12 50 26 39 25]
95
12
50.4
30.607842132368624


In [87]:
#o	Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.

array=np.arange(12)
k=array.reshape(3,4)
k

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
#o	Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
ones_array=np.ones((3,3))

one_d_array=np.array([1,2,3])
result=ones_array+one_d_array
result


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [89]:
#o	Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
arr=np.arange(1,51)
arr_divide_five=arr[arr%5==0]

arr_divide_five


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [90]:
#o	Create two 2x2 matrices and perform matrix multiplication.
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dot(arr1,arr2)
result

array([[19, 22],
       [43, 50]])

In [91]:
#o	Given a 4x4 array, use fancy indexing to extract the diagonal elements.
four_array=np.array([[1,2,3,4],[6,7,8,9,],[11,12,13,14],[16,17,18,19]])
diag=np.diagonal(four_array)
diag

array([ 1,  7, 13, 19])